### ISSUE TITLE
put of github-release fails with concourse 7.5.0

### ISSUE THREAD

**Issue by HemangLavana** [concourse/github-release-resource#112]
I have a put step of github release which fails with concourse 7.5.0 with the following error:

error running command: Field 'databaseId' doesn't exist on type 'Release'

If I downgrade back to 7.4.0, the same pipeline works.

Here's the part of the job that fails:
```
  - name: publish-release
    public: true
    plan:
      - in_parallel:
          - get: ws.ng-devops
          - get: version.python
            passed: [promote-python-image]
            trigger: true
      - put: release-python.ng-devops
        params:
          name: version.python/version
          tag: version.python/version
    on_failure: *send_email_on_failure
```

version.python is a semver resource. I have also filed https://github.com/concourse/concourse/discussions/7612, but I suspect this issue belongs here.

Let me know if you need more details.
