### ISSUE TITLE
Get  with dynamic/runtime release version. 

### ISSUE THREAD

**Issue by kvmw** [concourse/github-release-resource#113]
I've a scenario which i need to read the release version from a file in a repo and then download the that specific release artifacts.

I've tried the following approach:
```yaml
     - load_var: release-name
        file: source/release-name.yaml
      - get: gh-release
        version:
          tag: ((.:release-name.version.))
   ```
but apparently `get: gh-release`  needs to know the version during build preparation and therefore the workflow waits for ever with following message:
```gh-release - pinned version tag:((.:release-name.version)) not found```
