### ISSUE TITLE
Feature Request: Add "Generate release notes" option when creating a release

### ISSUE THREAD

**Issue by jessematlock** [concourse/github-release-resource#117]
Add an option to use Github's automatic release notes feature when creating a release.

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

```
- put: gh-release
  params:
    name: path/to/name/file
    tag: path/to/tag/file
    body: path/to/body/file
    drafts: true
    generate_release_notes: true
```

Notes:

* Would require updating [go-github library](https://github.com/google/go-github). The generate release note option is available in [v39.2.0](https://github.com/google/go-github/blob/d1858a3fc4bf8620cec6b7ed608a63de0572ce87/github/repos_releases.go#L29)
* * current version - `github.com/google/go-github/v39 v39.0.0`
* * upgrade version - `github.com/google/go-github/v39 v39.2.0`
* Should default to `false`
