### ISSUE TITLE
`version` file only contains last digit of semantic version, while `tag` is complete

### ISSUE THREAD

**Issue by crouth-redge** [concourse/github-release-resource#125]
### Describe the bug

Pretty simply summed up in this output from a task:

```
+ echo 'Checking contents of version vs tag'
Checking contents of version vs tag
+ cat gh-concourse-concourse-release/version
9
+ cat gh-concourse-concourse-release/tag
v6.7.9
```

### Reproduction steps

Pipeline for repoduction:

```yaml
resources:
  - name: gh-concourse-concourse-release
    type: github-release
    check_every: never
    source:
      owner: concourse
      repository: concourse
      access_token: ((redge_cicd_team_user_pa_token))
      tag_filter: "^v([^-]|-[^r]|-r[^c].)*$"
      
jobs:
  - name: example-job
     plan:
      - get: gh-concourse-concourse-release
      - task: fetch_thirdparty
        image: any_image_with_bash
        inputs:
        - name: gh-concourse-concourse-release
        run:
          path: script.sh
```

Script:

```bash
set -euox pipefail

echo "Checking contents of version vs tag"

cat "${CONCOURSE_PATH_PREFIX}/version"

cat "${CONCOURSE_PATH_PREFIX}/tag"

```

### Expected behavior

The `version` file should consistently have the complete version.

This bug seems to affect 100% of the projects we tested this against.

### Additional context

For those hitting this, you can workaround it by getting the contents of `tag` instead of `version`
