### ISSUE TITLE
`get` fails: grpc string contains invalid UTF-8 character

### ISSUE THREAD

**Issue by braunsonm** [concourse/github-release-resource#128]
### Describe the bug

I'm trying to use this resource to `get` a Github Release which I think contains a UTF-8 character (right-arrow)

The error I get during the `get` is:
```
set label: grpc: error while marshaling: string field contains invalid UTF-8: unknown
```

The configuration of the github release module is:

```yaml
  - name: knative-operator
    type: github-release
    icon: github
    check_every: 24h
    source:
      owner: knative
      repository: operator
      access_token: ((github_access_token))

...

- get: knative-operator
  trigger: true
  params:
    globs:
      - knative-operator-*.tgz
```

### Reproduction steps

1. Create a pipeline as described above
2. Run it
3. See the error in the `get` step

### Expected behavior

The `get` operation should complete successfully. Or a way to disable the body label.

### Additional context

I think this might be coming from the Github Release body containing an arrow. The release in question is here: https://github.com/knative/operator/releases/tag/knative-v1.13.0

**Comment by taylorsilva** [comment]
I think the error is actually coming from here: https://github.com/concourse/concourse/blob/05fce1356860277e3c851f2c5d2551bec34731cc/worker/runtime/container.go#L240-L243

Making a fix in concourse/concourse is probably better.

**Comment by scarytom** [comment]
I'm hitting this too, with:

```yml
- name: otel-java-instrumentation-github-release
  type: github-release
  icon: github
  source:
    owner: open-telemetry
    repository: opentelemetry-java-instrumentation
    tag_filter: "^v?(2\\.16\\.0)$"
```
The release notes for v2.16.0 contain a :toolbox: character, which Concourse barfs on.
