### ISSUE TITLE
Non-idempotent releases with same tag should fail

### ISSUE THREAD

**Issue by xinzweb** [concourse/github-release-resource#25]
We have the following snippet in our pipeline

``` yaml
  plan:
  - get: gpos_src
    passed:
    - gpos_centos5_release
  - get: bin_gpos_centos5_release
    passed:
    - gpos_centos5_release
    trigger: true
  - task: gpos_publish_tag
    file: gpos_src/concourse/publish_tag.yml
  - put: gpos_github_release
    params:
      name: gpos_github_release_stage/tag.txt
      tag: gpos_github_release_stage/tag.txt
      commitish: gpos_github_release_stage/commit.txt
      globs:
        - gpos_github_release_stage/bin_gpos_centos5_release.tar.gz
```

Currently if the job is triggered twice with:
1. different commits in `gpos_src`
2. different tar balls from `bin_gpos_centos5_release`
3. _same_ content in the `tag.txt` file

Then we observe the following behavior:
1. Both `put` will succeed
2. The value of the tag stays with the commit from the first `put`
3. The files attached are from the second `put`

Is it reasonable that we should expect the second `put` to flat out fail?
