### ISSUE TITLE
Filter checked versions by regex or prefix.

### ISSUE THREAD

**Issue by pivotal-jbarrett** [concourse/github-release-resource#38]
Add feature to filter versions by regex or at least prefix matching. For example if I wanted to fetch the latest 4.x version of a release.

```
- name: gh-release
  type: github-release
  source:
    version_match: '4\..*'
```
or
```
- name: gh-release
  type: github-release
  source:
    version_prefix: '4.'
```

The ultimate goal is that all versions returned by `check` will be major version 4.
