### ISSUE TITLE
Resource ignores tag and always pulls the latest

### ISSUE THREAD

**Issue by zmb3** [concourse/github-release-resource#39]
We are unable to pin to a specific release using this resource.

```
---
resources:
- name: concourse-release
  type: github-release
  source:
    user: concourse
    repository: concourse
    access_token: YOUR-GITHUB-ACCESS-TOKEN-GOES-HERE
jobs:
- name: test-concourse-release
  plan:
  - do:
    - get: concourse-release
      version: { tag: 'v2.4.0' }
    - task: test-release
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: ubuntu
        inputs:
        - name: concourse-release
        run:
          path: sh
          args:
          - -exc
          - |
            find .
            cat ./concourse-release/tag
            cat ./concourse-release/version
```

The output of this task is:
```
waiting for a suitable set of input versions
concourse-release - pinned version {"tag":"v2.4.0"} is not available
```

Even though the tag exists: https://github.com/concourse/concourse/releases/tag/v2.4.0

This behavior exists for other repos and tags as well.

**Comment by vito** [comment]
You have to run [`check-resource`](https://concourse.ci/fly-check-resource.html) to discover an older version.

**Comment by zmb3** [comment]
Thanks for clarifying.

Is this a desirable behavior?  Should a user have to run a manual command any time they want to use an older version?  I haven't seen other CI/CD tools behave this way.

**Comment by vito** [comment]
Well, when you put it that way, it's obviously not desireable, but it was much simpler to implement that way and get it out the door first. It mainly affects new pipelines, as versions are normally continuously detected over time. We'd welcome a PR to automatically `check` for pinned versions if they're not present, but our initial concern was with the complexity and performance implications involved.

**Comment by zmb3** [comment]
Understood, thanks.  I just wanted to make sure I wasn't missing something.  I may tackle that PR over the holidays.

**Comment by vito** [comment]
cool! would definitely help out a bunch of folks

**Comment by drnic** [comment]
Running concourse v2.5.1 I have the following job/resource but cannot figure out how to get it to load the desired version:

```
jobs:
- name: upgrade
  plan:
    - {get: ghost, trigger: true, version: { tag: '0.10.1' }}

resources:
- name: ghost
  type: github-release
  source:
    user: TryGhost
    repository: Ghost
```

After uploading the pipeline, it only fetches the latest version 0.11.4

![0.11.4](https://cl.ly/3M021i2B0U1y/download/Image%202017-01-20%20at%203.34.36%20PM.png)

I've tried the following `check-resource` commands:

```
fly -t vsphere check-resource -r $(basename $(pwd))/ghost
fly -t vsphere check-resource -r $(basename $(pwd))/ghost --from version:0.10.1
```

Ideas?
