### ISSUE TITLE
Publish a release not working

### ISSUE THREAD

**Issue by jonnyshaw89** [concourse/github-release-resource#44]
When i try to publish a release to GitHub i get the following error
`error running command: GET https://api.github.com/repos//DashVid-Uploader/releases: 404 Not Found []`

My resource is setup as follows

```
- name: gh-release
  type: github-release
  source:
    owner: JassoftLtd
    repository: DashVid-Uploader
    access_token: {{gh_access_token}}
```

It appears as though the owner isn't being put in the URL?
as `https://api.github.com/repos/JassoftLtd/DashVid-Uploader/releases` works for me

**Comment by wimpienortje** [comment]
I get the same error.

**Comment by wimpienortje** [comment]
Upgrading to concourse 2.7.3 fixes the issue.

**Comment by jonnyshaw89** [comment]
It didn't for me.

**Comment by peterellisjones** [comment]
We had the same issue when using `owner` but it worked fine when using the old field, `user`

```
- name: release
  type: github-release
  source:
    user: engineerbetter
    repository: concourse-up
    access_token: {{github_access_token}}
```
