### ISSUE TITLE
Failing to put release

### ISSUE THREAD

**Issue by pms1969** [concourse/github-release-resource#48]
I'm getting the following error when trying to put a release in a private repo.
`creating release ReleaseName
error running command: POST https://api.github.com/repos/my-org/my-repo/releases: 404 Not Found []`

prior to getting this error, I was getting:
`error running command: GET https://api.github.com/repos/my-org/my-repo.git/releases: 404 Not Found []`
so I know the get is now working, and it's something specific tot he POST.

My resource config is as follows (admittedly doctored to protect the innocent)
```
- name: gh-release
  type: github-release
  source:
    owner: my-org
    repository: my-repo
    access_token: {{access-token}}
```

and the put looks like this (again doctored):
```
    - put: gh-release
      params:
        name: package/name
        tag: version/version
        tag_prefix: package/tag-prefix
        commitish: package/commitish
        globs:
        - package/*.tar.gz
```

I know the access token works for the GET, and I've used it with curl successfully.

Any ideas what I might be doing wrong?
