### ISSUE TITLE
Latest version fetching failing

### ISSUE THREAD

**Issue by tinygrasshopper** [concourse/github-release-resource#56]
Hello!

We think we are configuring our concourse pipeline correctly to pick up our latest release, but we are getting an error. 

Resource:
```
- name: bbr-binary-release
  type: github-release
  source:
      owner: cloudfoundry-incubator
      repository: bosh-backup-and-restore
```

Used in plan as
```
  - get: bbr-binary-release
    trigger: true
```

According to the readme:
> If the version is not specified, the latest version is chosen using semver semantics.

We want it to fetch the latest (non-draft) release, and our release tags look like they are [semver-compatible](https://github.com/cloudfoundry-incubator/bosh-backup-and-restore/releases)

But when it runs in concourse, we get the following error
> error running command: GET https://api.github.com/repos/cloudfoundry-incubator/bosh-backup-and-restore/releases/0: 404 Not Found []

cc: @flangewad
