### ISSUE TITLE
Failed to create github final release with 404 error 

### ISSUE THREAD

**Issue by bobhlo** [concourse/github-release-resource#6]
ci/pipeline.yml
```
- name: github-final-release
  type: github-release
  source:
    github_api_url: https://github.build.ge.com/api/v3/
    user: industry-cloud-cf
    repository: cf-sensu-client-release
    access_token: {{github-access-token}}
```
github-final-release error reported 
```
error running command: GET https://github.build.ge.com/api/v3/repos/industry-cloud-cf/cf-sensu-client-release/releases: 404 Not Found []

resource script '/opt/resource/out [/tmp/build/put]' failed: exit status 1
```
