### ISSUE TITLE
github release creation fails - invalid Message

### ISSUE THREAD

**Issue by drahnr** [concourse/github-release-resource#65]
On every attempt to push to make a github release this error pops up:
```
POST https://api.github.com/repos/drahnr/oregano/releases: 422 Validation Failed [{Resource:Release Field:target_commitish Code:invalid Message:}]
```

https://ci.spearow.io/teams/main/pipelines/oregano/jobs/make-release/builds/14

https://screenshots.firefox.com/BazokjFlfCeCyiHN/ci.spearow.io

```
fly -t spearow hijack -j oregano/make-release                                                                                      1: build #14, step: gh-release, type: put
2: build #14, step: tag2file, type: task
choose a container: 2
[root@5c9cc5a8-543d-4228-563c-c1b6d9905eac 64658831]# cat 
deb-release/      git-tag-resource/ release-info/     rpm-release/      source-release/   
[root@5c9cc5a8-543d-4228-563c-c1b6d9905eac 64658831]# cat release-info/
cat: release-info/: Is a directory
[root@5c9cc5a8-543d-4228-563c-c1b6d9905eac 64658831]# cat release-info/
BODY       COMMITISH  NAME       TAG        
[root@5c9cc5a8-543d-4228-563c-c1b6d9905eac 64658831]# cat release-info/
BODY       COMMITISH  NAME       TAG        
[root@5c9cc5a8-543d-4228-563c-c1b6d9905eac 64658831]# cat release-info/*
Yet another release
9c14571
oregano
0.84.21
```

Local check
```
#git log -n1

commit 9c14571b0cf6b693cb8df5bb85439431aba05a34 (HEAD -> master, tag: v0.84.21, origin/master, origin/HEAD)
Author: Bernhard Schuster <bernhard@ahoi.io>
Date:   Sat Dec 16 10:11:21 2017 +0100

    version/bump: v0.84.21
```

Relevant concourse.yml

```
resources:
- name: git-tag-resource
  type: git
  source:
    tag_filter: "v[0-9]*"
    branch: master
    uri: https://github.com/drahnr/oregano.git

- name: gh-release
  type: github-release
  source:
    owner: drahnr
    repository: oregano
    access_token: {{drahnr-github-token}}

-jobs:
  - name: make-release
    build_logs_to_retain: 5
    public: true
    plan:
    - aggregate:
      - get: git-tag-resource
        passed: [source-release,build-pkg-rpm-release, build-pkg-deb-release]
        trigger: true
      - get: oregano-test-fedora
      - get: source-release
        passed: [source-release]
      - get: rpm-release
        passed: [build-pkg-rpm-release]
      - get: deb-release
        passed: [build-pkg-deb-release]
    - task: tag2file
      timeout: 5m
      image: oregano-test-fedora
      config:
        platform: linux
        inputs:
        - name: git-tag-resource
        - name: source-release
        - name: deb-release
        - name: rpm-release
        outputs:
        - name: release-info
        run:
          path: sh
          args:
          - -exc
          - |
            git log -n 1 --format="%h" HEAD > ../release-info/COMMITISH
            ./waf version
            cat VERSION > ../release-info/TAG
            echo "oregano" > ../release-info/NAME
            echo "Yet another release" > ../release-info/BODY
          dir: git-tag-resource
    - put: gh-release
      params:
        tag_prefix: v
        name: release-info/NAME
        tag: release-info/TAG
        body: release-info/BODY
        commitish: release-info/COMMITISH
        globs:
        - source-release/oregano-*.tar.xz
        - rpm-release/oregano-*.rpm
        - deb-release/oregano_*.deb
```
