### ISSUE TITLE
Get latest from github-api-url/latest instead of github-api-url/0

### ISSUE THREAD

**Issue by genevieve** [concourse/github-release-resource#66]
Instead of specifying the latest release and having to update it every time, the resource could pick up the latest.

Currently a new github-release resource tries to query:

https://api.github.com/repos/cloudfoundry/cf-deployment-concourse-tasks/releases/0

This fails with a 404. It should check [/latest](https://developer.github.com/v3/repos/releases/#get-the-latest-release) when no release version is specified in the resource:

https://api.github.com/repos/cloudfoundry/cf-deployment-concourse-tasks/releases/latest

**Comment by combor** [comment]
It's failing for us as well:
```
error running command: GET https://api.github.com/repos/pivotal/postfacto/releases/0: 404 Not Found []
```

**Comment by DanielJonesEB** [comment]
Seeing the same issue here, but the `get` has been configured with a `version`:

```
- name: control-tower-release
  type: github-release
  source:
    pre_release: true
    repository: control-tower
    user: engineerbetter
...

  plan:
  - get: control-tower-release
    version:
      tag: 0.4.1
```

Resultant error on `get`:

```
error running command: GET https://api.github.com/repos/engineerbetter/control-tower/releases/0: 404 Not Found []
```
