### ISSUE TITLE
Failed to upload release to github with 401 bad credentials

### ISSUE THREAD

**Issue by bobhlo** [concourse/github-release-resource#7]
Able to access the repo with security token, however failed to upload release to github.

```
curl https://{github-access-token}:@github.build.ge.com/api/v3/repos/industrial-cloud-cf/cf-sensu-client-release/releases
```
```
- name: github-final-release
  type: github-release
  source:
    github_api_url: https://github.build.ge.com/api/v3/
    user: industrial-cloud-cf
    repository: cf-sensu-client-release
    access_token: {{github-access-token}}
```

creating release cf-sensu-client-release v1.6.0
uploading /tmp/build/put/create-final-release/boshrelease/releases/cf-sensu-client/cf-sensu-client-1.6.0.tgz
error running command: POST https://uploads.github.com/repos/industrial-cloud-cf/cf-sensu-client-release/releases/547/assets?name=cf-sensu-client-1.6.0.tgz: 401 Bad credentials []

resource script '/opt/resource/out [/tmp/build/put]' failed: exit status 1
