### ISSUE TITLE
Auto-unpack source tarball/zip

### ISSUE THREAD

**Issue by aegershman** [concourse/github-release-resource#73]
I'm under the impression the [Concourse s3 resource can unpack source tarballs](https://github.com/concourse/s3-resource#parameters) on download. I have the same use case for download gh-release source code-- I would like to download the release source code & have it automatically unpacked in the same directory. 

Currently I'm implementing the logic in a task, but it would save me quite a bit of code if the source code contents could be untarred/unzipped automatically.

```
      - task: unpack-tarball
        config:
          platform: linux
          image_resource:
            type: docker-image
            source: {repository: czero/cflinuxfs2}
          inputs: [name: tarball]
          outputs: [name: untarred]
          run:
            path: bash
            args: [-c, tar -xvf tarball/*.tar.gz -C untarred --strip-components=1]
```

Thanks for your time & consideration
