### ISSUE TITLE
failing to discover previous versions

### ISSUE THREAD

**Issue by eedwards-sk** [concourse/github-release-resource#76]
```
- name: homebrew
  type: github-release
  check_every: 12h
  source:
    owner: Homebrew
    repository: brew
```

This only reports the latest version available which is preventing me from going back to a previous version (the latest version has broken me).

e.g. the above resource currently sees version `1.7.2` but I need `1.7.1`
