### ISSUE TITLE
globs - 502 Error Creating Policy

### ISSUE THREAD

**Issue by Jarlotee** [concourse/github-release-resource#80]
When trying to upload a .tar.gz file no mime type is being sent to github and it returns a 502

Example
```yaml
 - put: github-pre-release
    params:
      name: version/name
      tag: version/number
      body: version/body
      commitish: source-code/.git/ref
      globs:
        - artifacts/*.tar.gz
```

It appears that the container is missing required system files to determine mime type:

go-github source code
https://github.com/google/go-github/blob/master/github/repos_releases.go#L358

go example
https://play.golang.org/p/3-HK1GnnMDl

mime source
https://golang.org/pkg/mime/#TypeByExtension
