### ISSUE TITLE
"release: false" in Source configuration doesn't have any effect

### ISSUE THREAD

**Issue by arutsudar** [concourse/github-release-resource#95]
In Readme, it says, 

> release: Optional. Default true. When set to true, put produces release and check detects releases. **If false, put and check will ignore releases.** Note that releases must have semver compliant tags to be detected.

When trying this below concourse deployment yaml,

```
---
resources:
- name: git-REPOSITORY_NAME-version
  type: git
  source:
    uri: git@github.com:OWNER_NAME/REPOSITORY_NAME.git
    branch: Version
    private_key: {{rsa-key}}

- name: res-github-release-REPOSITORY_NAME
  type: github-release
  source:
    owner: OWNER_NAME
    repository: REPOSITORY_NAME
    release: false
    access_token: ACCESS_TOKEN

jobs:
- name: Create Tag
  plan:
  - get: git-REPOSITORY_NAME-version
  - put: res-github-release-REPOSITORY_NAME
    params:
      name: git-REPOSITORY_NAME-version/version1/version1.txt
      tag: git-REPOSITORY_NAME-version/version1/version1.txt
```

I was expecting only the tag to be created.
(Note "release: false" in the github-release resource.)

But it creates both tag and a release, even though release is set as false. Or, am I not understanding the explanation correctly?
